config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'admin/dashboard#index'

  authenticated :admin, lambda { |u| u.email }  do
    mount Sidekiq::Web => '/sidekiq'
    apipie
  end

  devise_for :admins,
             skip: [:registrations, :passwords],
             controllers: {
                 registrations: 'admin/registrations',
                 sessions:      'admin/sessions'
             }

  devise_for :merchants,
             skip: [:registrations, :sessions, :passwords]

  devise_for :customers,
             skip: [:registrations, :sessions, :passwords]




  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do

      namespace :customers, path: '/c' do
        resources :auth, only: [] do
          collection do
            post :register, action: :register
            post :login, action: :login
            delete :logout, action: :logout
          end
        end

        resources :categories, only: :index do
          get :deals, action: :category_deals
        end

        resources :purchases, only: :create do
          collection do
            get :history, action: :history
          end
        end
      end

      namespace :merchants, path: '/m' do
        resources :auth, only: [] do
          collection do
            post :login, action: :login
            post :register, action: :register
            delete :logout, action: :logout
          end
        end
      end

    end
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :categories
    resources :users
    resources :customers
    resources :merchants
    resources :deals

  end
end

app/models/category.rb
class Category < ApplicationRecord

  # Uploaders
  mount_uploader :image, CategoryImageUploader

  # Relations
  has_many :deals, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    merchants_collection = Category.order(id: :desc)
                                   .page(params[:page])
                                   .per(20)
    render_template!(:landing, decor_categories: CategoryDecorator.decorate_collection(merchants_collection))
  end

  def new
    render_template!(:new, new_category: Category.new)
  end

  def edit
    render_template!(:edit, decor_category: @category.decorate)
  end

  def create
    new_category = Category.new(category_params)

    if new_category.save
      redirect_to admin_categories_path, notice: 'Category was successfully created.'
    else
      render_template!(:new, new_category: new_category)
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: 'Category was successfully updated.'
    else
      render_template!(:edit, decor_category: @category.decorate)
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, notice: 'Category was successfully destroyed.'
  end



  private

  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :image)
  end
end

app/controllers/api/v1/customers/categories_controller.rb
module Api
  module V1
    class Customers::CategoriesController < Customers::BaseController
      extend Controllers::ApiDoc
      expose_doc

      skip_before_action :authenticate_customer!

      def index
        success! categories: Category.all
                                     .map { |cat| CategorySerializer.new(cat)}
      end

      def category_deals
        category = Category.find(params[:category_id])

        # Should be refactored in future!
        # Show all deals for 'All' category only in angular coordinates!
        category_deals = category.name.eql?('All') ? Deal.all : category.deals

        success! deals: category_deals.includes(:merchant)
                                      .map { |deal| DealSerializer.new(deal) }
      rescue ActiveRecord::RecordNotFound => e
        throw_error!(status: :not_found, details: e.message)
      end
    end
  end
end

app/views/admin/categories/landing/landing.haml
.row
  .col-lg-12
    .card
      .card-header
        %i.fa.fa-briefcase
        Categories List

        = link_to 'New Category', new_admin_category_path, class: 'btn btn-primary pull-right'
      .card-body
        %table.table.table-responsive-lg.table-hover.table-striped
          %thead
            %tr
              %th Name
              %th Image
              %th Created at
              %th
          %tbody
            - decor_categories.each do |category|
              %tr
                %td= category.name
                %td= cl_image_tag(category.image.url, width: 100, height: 100, crop: :fill)
                %td= category.created_at_formated
                %td
                  = link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-warning btn-xs'
                  = link_to 'Destroy', edit_admin_category_path(category), method: :delete, data: {confirm: 'You will destroy ALL deals related with this Category! Are you sure!?'}, class: 'btn btn-danger btn-xs'

        = render partial: 'admin/shared_components/paginate/paginate', locals: { collection: decor_categories }