config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'admin/dashboard#index'

  authenticated :admin, lambda { |u| u.email }  do
    mount Sidekiq::Web => '/sidekiq'
    apipie
  end

  devise_for :admins,
             skip: [:registrations, :passwords],
             controllers: {
                 registrations: 'admin/registrations',
                 sessions:      'admin/sessions'
             }

  devise_for :merchants,
             skip: [:registrations, :sessions, :passwords]

  devise_for :customers,
             skip: [:registrations, :sessions, :passwords]




  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do

      namespace :customers, path: '/c' do
        resources :auth, only: [] do
          collection do
            post :register, action: :register
            post :login, action: :login
            delete :logout, action: :logout
          end
        end

        resources :categories, only: :index do
          get :deals, action: :category_deals
        end

        resources :purchases, only: :create do
          collection do
            get :history, action: :history
          end
        end
      end

      namespace :merchants, path: '/m' do
        resources :auth, only: [] do
          collection do
            post :login, action: :login
            post :register, action: :register
            delete :logout, action: :logout
          end
        end
      end

    end
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :categories
    resources :users
    resources :customers
    resources :merchants
    resources :deals

  end
end

app/views/admin/shared_components/header/_header.html.haml
%header.app-header.navbar
  %button.navbar-toggler.sidebar-toggler.d-lg-none.mr-auto{"data-toggle" => "sidebar-show", :type => "button"}
    %span.navbar-toggler-icon
  = link_to 'Neario', '/', class: 'navbar-brand'
  %button.navbar-toggler.sidebar-toggler.d-md-down-none{"data-toggle" => "sidebar-lg-show", :type => "button"}
    %span.navbar-toggler-icon

  %ul.nav.navbar-nav.d-md-down-none
    %li.nav-item.px-3
      = link_to 'Api Docs', apipie_apipie_path, class: 'nav-link', target: '_blank', rel: 'nofollow'
    %li.nav-item.px-3
      = link_to 'Sidekiq Workers', sidekiq_web_path, class: 'nav-link', target: '_blank', rel: 'nofollow'


  %ul.nav.navbar-nav.ml-auto
    %li.nav-item
      .btn-group{"aria-label" => "Button group", :role => "group"}
        = link_to '#', class:'btn', data: { turbolinks: false } do
          %i.icon-user
          = current_admin.email

        = link_to destroy_admin_session_path, class:'btn', method: :delete do
          %i.fa.fa-lock
          Logout